# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Donnie Cameron
tagline:          'MRI physicist'
description:      'MRI physicist, researcher and expert in musculo-skeletal imaging and spectroscopy'
url:              https://dc-3t.github.io/
baseurl:          /DC-3T.github.io

author:
  name:           'Donnie Cameron'
  url:            

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/DC-3T
